services:
  database:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: db_paybills
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: paybills-api
    restart: always
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/db_paybills
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: true
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs

volumes:
  pg_data:
